prompt = "sum of 2 and 3"
chosen_def = "fn_add_number"
param_prom :list[str] = [
        "Generate a valid JSON object with exactly three keys: prompt, ",
        "name (the chosen function), and parameters. ",
        "You must choose the function whose description best matches the ",
        "user's request. ",
        "Rules: ",
        '- If the request says "replace all numbers", use regex "[0-9]+". ',
        "Example output: ",
        '{"prompt":"Compute the sum of 15 and 27",',
        '"name":"fn_add_numbers",',
        '"parameters":{"a":15,"b":27}} ',
        "Example 2: ",
        '{"prompt":"Replace every sequence of digits in \'Order 512 ',
        "costs 49 dollars' with <NUM>",
        ',"name":"fn_substitute_string_with_regex",',
        '"parameters":{',
        '"source_string":"Order 512 costs 49 dollars",',
        '"regex":"[0-9]+",',
        '"replacement":"<NUM>"',
        '}} ',
        "Example 3: ",
        '{"prompt":"Replace every vowel in \'Artificial Intelligence\' ',
        '"with *",',
        '"name":"fn_substitute_string_with_regex",',
        '"parameters":{',
        '"source_string":"Artificial Intelligence",',
        '"regex":"[AEIOUaeiou]",',
        '"replacement":"*"',
        '}} ',
        "Example 4: ",
        '{"prompt":"Replace every occurrence of \'apple\' with \'orange\' ',
        "in 'apple pie and apple juice'",
        '"name":"fn_substitute_string_with_regex",',
        '"parameters":{',
        '"source_string":"apple pie and apple juice",',
        '"regex":"apple",',
        '"replacement":"orange"',
        '}} ',
        '{"prompt":"',prompt,'",',
        '"name":"',chosen_def,'",',
        '"parameters":'
    ]
print("".join(param_prom))